// Auto-generated by tauri-specta. DO NOT EDIT.
// Regenerate via `pnpm gen:bindings`.
// Source of truth: src-tauri/src/shared/types.rs + #[tauri::command] signatures.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	exitApp: () => __TAURI_INVOKE<void>("exit_app"),
	showSettingsWindow: () => typedError<null, string>(__TAURI_INVOKE("show_settings_window")),
	fitPanel: (height: number | null) => typedError<null, string>(__TAURI_INVOKE("fit_panel", { height })),
	getConfig: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("get_config", { key })),
	setConfig: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("set_config", { key, value })),
	getTimerState: () => typedError<TimerStatePayload, string>(__TAURI_INVOKE("get_timer_state")),
	startWork: () => typedError<null, string>(__TAURI_INVOKE("start_work")),
	confirmBreak: () => typedError<null, string>(__TAURI_INVOKE("confirm_break")),
	confirmReturn: () => typedError<null, string>(__TAURI_INVOKE("confirm_return")),
	togglePause: () => typedError<null, string>(__TAURI_INVOKE("toggle_pause")),
	reset: () => typedError<null, string>(__TAURI_INVOKE("reset")),
	manualBreak: () => typedError<null, string>(__TAURI_INVOKE("manual_break")),
	skipBreak: () => typedError<null, string>(__TAURI_INVOKE("skip_break")),
};

/* Types */
/**
 *  set_config 命令成功后通过 `config-changed` 事件广播给所有窗口的载荷。
 *  订阅方（AppThemeProvider / AppI18nProvider）据此响应配置变化。
 */
export type ConfigChangedPayload = {
	/**  变更的配置 key（与 src/shared/config.ts 中的 *_KEY 常量对齐）。 */
	key: string,
	/**  新值（配置统一以字符串形式存储，订阅方按 key 自行 decode）。 */
	value: string,
};

/**
 *  当前状态机阶段。前端 PanelApp 据此切换 5 种 UI 分支
 *  （Working/Alerting/Breaking/Waiting/Paused 各一个视图）。
 */
export type Phase = "working" | "alerting" | "breaking" | "waiting" | "paused";

/**  timer-tick / phase-changed 事件 + get_timer_state 命令的统一 payload。 */
export type TimerStatePayload = {
	/**  当前状态机阶段。 */
	phase: Phase,
	/**
	 *  切换前的阶段。仅在 phase-changed 事件中有意义（前端做过渡动画 / 判断进入 vs 离开）；
	 *  timer-tick 与 get_timer_state 中恒为 None。
	 */
	prevPhase: Phase | null,
	/**
	 *  本阶段剩余秒数。working / breaking 阶段倒计时核心字段：
	 *  前端圆环进度 = remaining / total，中央显示 MM:SS。
	 */
	remainingSeconds: number,
	/**
	 *  本轮总秒数（work_duration 或 break_duration / long_break_duration 换算成秒）。
	 *  UI 圆环进度分母，与 remaining_seconds 配合算百分比。
	 */
	totalSeconds: number,
	/**
	 *  当前随机抽取的随笔心语文案（whisper 池）。alerting 阶段大字显示唤起注意，breaking 阶段小字辅助；
	 *  working / waiting / paused 阶段为空字符串。
	 */
	currentWhisperReminder: string,
	/**
	 *  当前随机抽取的健康提醒文案（health 池）。breaking 阶段在 BreakingView 以绿色横幅展示；
	 *  alerting 阶段已抽取但暂不展示；working / waiting / paused 阶段为空字符串。
	 */
	currentHealthReminder: string,
	/**  本次休息是否为长休息。前端 breaking UI 据此显示「休息中」/「长休息中」标签与不同配色。 */
	isLongBreak: boolean,
	/**
	 *  跳过休息的累计点击次数。前端 breaking 阶段按钮显示「跳过 (n/max)」；
	 *  达到 break_skip_max 配置门槛才真正跳过。进入 breaking 时清零。
	 */
	breakSkipCount: number,
	/**
	 *  今日累计「真正跳过休息」的次数（break_skip_count 达到 break_skip_max 才计一次）。
	 *  持久化到 config 表 today_skip_count（{date,count} JSON），跨天自动归零。
	 *  与 break_skip_count（单次休息防误触、进休息清零、不持久化）严格区分。
	 *  AlertingView 据此 + skip_count_reminder 阈值决定是否显示「今日多次跳过休息」警示横幅。
	 */
	todaySkipCount: number,
	/**
	 *  已完成的工作-休息轮数。长休息判定输入：
	 *  `completed_cycles > 0 && completed_cycles % interval == 0`；
	 *  仅正常完成 on_break_done 才递增，跳过休息不计入。
	 */
	completedCycles: number,
	/**  当前 Paused 是否由 quietHours 静音时段触发（vs 用户手动暂停）。 */
	quietTriggered: boolean,
	/**
	 *  Breaking 阶段是否因检测到鼠标活动而软暂停（不切 phase，仅冻结倒计时）。
	 *  前端 BreakingView 据此显隐「检测到操作，倒计时已暂停」横幅。
	 */
	breakPaused: boolean,
};

/**
 *  Y/N 布尔约定的 SSOT。
 * 
 *  serde rename 决定 DB 存储格式（"Y"/"N"）+ 前端 bindings.ts 字面量联合类型。
 *  前端 src/shared/config.ts 的 YES_NO 运行时对象受此类型约束
 */
export type YesNo = "Y" | "N";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

