// Auto-generated by tauri-specta. DO NOT EDIT.
// Regenerate via `pnpm gen:bindings`.
// Source of truth: src-tauri/src/shared/types.rs + #[tauri::command] signatures.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	exitApp: () => __TAURI_INVOKE<void>("exit_app"),
	showSettingsWindow: (navigateTo: string | null) => typedError<null, string>(__TAURI_INVOKE("show_settings_window", { navigateTo })),
	fitPanel: (height: number | null) => typedError<null, string>(__TAURI_INVOKE("fit_panel", { height })),
	getPanelForm: () => __TAURI_INVOKE<PanelForm>("get_panel_form"),
	getAppConfig: (key: string) => typedError<string | null, string>(__TAURI_INVOKE("get_app_config", { key })),
	setAppConfig: (key: string, value: string) => typedError<null, string>(__TAURI_INVOKE("set_app_config", { key, value })),
	getTimerState: () => typedError<TimerStatePayload, string>(__TAURI_INVOKE("get_timer_state")),
	startWork: () => typedError<null, string>(__TAURI_INVOKE("start_work")),
	confirmBreak: () => typedError<null, string>(__TAURI_INVOKE("confirm_break")),
	confirmReturn: () => typedError<null, string>(__TAURI_INVOKE("confirm_return")),
	togglePause: () => typedError<null, string>(__TAURI_INVOKE("toggle_pause")),
	reset: () => typedError<null, string>(__TAURI_INVOKE("reset")),
	manualBreak: () => typedError<null, string>(__TAURI_INVOKE("manual_break")),
	skipBreak: () => typedError<null, string>(__TAURI_INVOKE("skip_break")),
};

/* Constants */
export const BREAK_DURATION_KEY = "break_duration" as const;

export const BREAK_SKIP_MAX_KEY = "break_skip_max" as const;

export const DEFAULT_BREAK_DURATION = 1 as const;

export const DEFAULT_BREAK_SKIP_MAX = 1 as const;

export const DEFAULT_DND_HOURS = [] as const;

export const DEFAULT_DND_HOURS_ENABLED = false as const;

export const DEFAULT_HEALTH_TEXTS = ["起来走走，活动一下身体","远眺窗外，放松眼睛","喝杯水，补充水分","做几个简单的拉伸动作","深呼吸，放松身心","活动手腕，预防鼠标手","闭眼休息，让大脑放松","伸展脊柱，改善坐姿"] as const;

export const DEFAULT_IDLE_PAUSE_THRESHOLD = 60.0 as const;

export const DEFAULT_LANGUAGE = "system" as const;

export const DEFAULT_LAUNCH_AT_LOGIN = false as const;

export const DEFAULT_LONG_BREAK_DURATION = 5 as const;

export const DEFAULT_LONG_BREAK_ENABLED = true as const;

export const DEFAULT_LONG_BREAK_INTERVAL = 2 as const;

export const DEFAULT_LONG_BREAK_WINDOW = "tray" as const;

export const DEFAULT_PAUSE_ON_IDLE = true as const;

export const DEFAULT_QUIET_HOURS = [{"end":"14:00","start":"12:00"},{"end":"18:30","start":"18:00"}] as const;

export const DEFAULT_QUIET_HOURS_ENABLED = true as const;

export const DEFAULT_QUIET_WINDOW = "tray" as const;

export const DEFAULT_REST_CONFIRM = true as const;

export const DEFAULT_REST_END_CONFIRM = true as const;

export const DEFAULT_REST_WINDOW = "tray" as const;

export const DEFAULT_WHISPER_TEXTS = ["成功只有一个 ———— 按照自己的方式，去度过人生。","世界上只有一种真正的英雄主义，那就是在认清生活的真相后依然热爱生活。","这个世界上有很多人，很多种选择，最低的是温饱，然后是利益，就是钱，超越钱的，是名望、权利，但是在超越这些所有东西之上还有一样东西，叫智慧。... 因为我知道我懂的越来越多，只有智慧和知识，内在强大，让你自己懂得很多，对这个世界你有充分的了解，你就不会有畏惧。","因为我要告诉你，所谓千秋霸业，万古流芳，以及一切的一切，只是粪土。先变成粪，再变成土。现在你不明白，将来你会明白，将来不明白，就再等将来，如果一辈子都不明白，也行。","长期的困难生活，最能磨炼一个人的意志。有很多人在遇到困难后，只能怨天尤人，得过且过，而另外一些人虽然也不得不在困难面前低头，但他们的心从未屈服，他们不断地努力，相信一定能够取得最后的胜利。","当你感到畏惧和痛苦，支撑不下去的时候，你应该同时意识到，决定你命运的时候到了。 因为畏惧并不是消极的，事实上，它是一个人真正强大的开始，也是成为英雄的起点。 不懂得畏惧的人不知道什么是困难，也无法战胜困难。 只有懂得畏惧的人，才能唤起自己的力量。 只有懂得畏惧的人，才有勇气去战胜畏惧。 懂得畏惧的可怕，还能超越它、征服它的人，就是英雄。","所谓道，是天下所有规律的总和，是最根本的法则，只要能够了解道，就可以明了世间所有的一切。","滚滚长江东逝水，浪花淘尽英雄。是非成败转头空，青山依旧在，几度夕阳红。 白发渔樵江渚上，惯看秋月春风。一壶浊酒喜相逢，古今多少事，都付笑谈中。","无论有多么伟大正直的理想，要实现它，还必须懂得两个字——变通。只有变通，只有切合实际的行动，才能适应这个变化万千的世界。"] as const;

export const DEFAULT_WORK_DURATION = 30 as const;

export const DND_HOURS_ENABLED_KEY = "dnd_hours_enabled" as const;

export const DND_HOURS_KEY = "dnd_hours" as const;

export const EVENT_APP_CONFIG_CHANGED = "app-config-changed" as const;

export const EVENT_PANEL_FORM_CHANGED = "panel-form-changed" as const;

export const EVENT_PHASE_CHANGED = "phase-changed" as const;

export const EVENT_SETTINGS_NAVIGATE = "settings:navigate" as const;

export const EVENT_TIMER_TICK = "timer-tick" as const;

export const IDLE_PAUSE_THRESHOLD_KEY = "idle_pause_threshold" as const;

export const LANGUAGE_KEY = "language" as const;

export const LAUNCH_AT_LOGIN_KEY = "launch_at_login" as const;

export const LONG_BREAK_DURATION_KEY = "long_break_duration" as const;

export const LONG_BREAK_ENABLED_KEY = "long_break_enabled" as const;

export const LONG_BREAK_INTERVAL_KEY = "long_break_interval" as const;

export const LONG_BREAK_WINDOW_KEY = "long_break_window" as const;

export const MAX_BREAK_SKIP_MAX = 3 as const;

export const MAX_IDLE_PAUSE_THRESHOLD = 300.0 as const;

export const MIN_BREAK_SKIP_MAX = 1 as const;

export const MIN_IDLE_PAUSE_THRESHOLD = 30.0 as const;

export const PAUSE_ON_IDLE_KEY = "pause_on_idle" as const;

export const QUIET_HOURS_ENABLED_KEY = "quiet_hours_enabled" as const;

export const QUIET_HOURS_KEY = "quiet_hours" as const;

export const QUIET_WINDOW_KEY = "quiet_window" as const;

export const REMINDERS_KEY = "reminders" as const;

export const REST_CONFIRM_KEY = "rest_confirm" as const;

export const REST_END_CONFIRM_KEY = "rest_end_confirm" as const;

export const REST_WINDOW_KEY = "rest_window" as const;

export const WORK_DURATION_KEY = "work_duration" as const;

/* Types */
/**
 *  set_app_config 命令成功后通过 `app-config-changed` 事件广播给所有窗口的载荷。
 *  订阅方（AppThemeProvider / AppI18nProvider）据此响应配置变化。
 */
export type AppConfigChangedPayload = {
	/**  变更的配置 key（与 src/shared/appConfig.ts 中的 *_KEY 常量对齐）。 */
	key: string,
	/**  新值（配置统一以字符串形式存储，订阅方按 key 自行 decode）。 */
	value: string,
};

/**
 *  panel 窗口当前形态（贴托盘 / 屏幕右上角 / 全屏强制）。
 *  受管状态（app.manage）：phase-changed 监听器按 rest_window / long_break_window / quiet_window 配置写入，
 *  show_panel / fit_panel / create_panel / settings 恢复等所有定位路径统一读取，
 *  保证高度自适应、窗口恢复后不跳回托盘位。
 */
export type PanelForm = 
/**  贴托盘图标旁（现有默认形态）。 */
"tray" | 
/**  托盘所在屏 work_area 右上角。 */
"topRight" | 
/**
 *  伪全屏：窗口铺满托盘所在屏 work_area（盖住菜单栏下方全部可用区域，置顶无装饰）。
 *  Alerting 起接管，Working（跳过 / 我回来了 / 重置）时退出并恢复小窗。
 *  不用原生 set_fullscreen：对 borderless+transparent 窗口会补装标题栏装饰且
 *  异步时序与 show/set_focus 竞争出「带标题栏的 maximized」污染形态（实测）。
 */
"fullscreen";

/**
 *  当前 Paused 阶段的触发来源（仅 phase == Paused 时有意义，其余阶段恒为 Manual 惯例值）。
 *  前端 PausedView 据此三态分派展示；panel.rs 据此决定弹窗 / 收起；tick 据此决定恢复规则。
 */
export type PauseSource = 
/**  用户手动暂停（toggle_pause）：不自动恢复，等用户点继续。 */
"manual" | 
/**  休息时段（quiet_hours）命中：打断式（弹窗常驻），时段全部结束后自动 start_work 全新一轮。 */
"quiet" | 
/**  免打扰时段（dnd_hours）命中：非打断式（收起不弹，托盘可查看），时段全部结束后自动 start_work 全新一轮。 */
"dnd";

/**
 *  当前状态机阶段。前端 PanelApp 据此切换 5 种 UI 分支
 *  （Working/Alerting/Breaking/Waiting/Paused 各一个视图）。
 */
export type Phase = "working" | "alerting" | "breaking" | "waiting" | "paused";

/**
 *  时段单条 {start, end}（"HH:mm"，支持跨午夜 start > end）。
 *  quiet_hours 配置 JSON 的 schema + DEFAULT_QUIET_HOURS 常量导出共用；
 *  前端 appConfig.ts 的 QuietHourPeriod / decodeQuietHours 与此对齐。
 *  字段用 &'static str 而非 String：DEFAULT_QUIET_HOURS 是 const 表达式，
 *  String 分配不能出现在 const 上下文；serde/序列化行为等价。
 */
export type QuietHourPeriod = {
	start: string,
	end: string,
};

/**  timer-tick / phase-changed 事件 + get_timer_state 命令的统一 payload。 */
export type TimerStatePayload = {
	/**  当前状态机阶段。 */
	phase: Phase,
	/**
	 *  切换前的阶段。仅在 phase-changed 事件中有意义（前端做过渡动画 / 判断进入 vs 离开）；
	 *  timer-tick 与 get_timer_state 中恒为 None。
	 */
	prevPhase: Phase | null,
	/**
	 *  本阶段剩余秒数。working / breaking 阶段倒计时核心字段：
	 *  前端圆环进度 = remaining / total，中央显示 MM:SS。
	 */
	remainingSeconds: number,
	/**
	 *  本轮总秒数（work_duration 或 break_duration / long_break_duration 换算成秒）。
	 *  UI 圆环进度分母，与 remaining_seconds 配合算百分比。
	 */
	totalSeconds: number,
	/**
	 *  当前随机抽取的随笔心语文案（whisper 池）。alerting 阶段大字显示唤起注意，breaking 阶段小字辅助；
	 *  working / waiting / paused 阶段为空字符串。
	 */
	currentWhisperReminder: string,
	/**
	 *  当前随机抽取的健康提醒文案（health 池）。breaking 阶段在 BreakingView 以绿色横幅展示；
	 *  alerting 阶段已抽取但暂不展示；working / waiting / paused 阶段为空字符串。
	 */
	currentHealthReminder: string,
	/**  本次休息是否为长休息。前端 breaking UI 据此显示「休息中」/「长休息中」标签与不同配色。 */
	isLongBreak: boolean,
	/**
	 *  跳过休息的累计点击次数。前端 breaking 阶段按钮显示「跳过 (n/max)」；
	 *  达到 break_skip_max 配置门槛才真正跳过。进入 breaking 时清零。
	 */
	breakSkipCount: number,
	/**
	 *  今日累计「真正跳过休息」的次数（break_skip_count 达到 break_skip_max 才计一次）。
	 *  持久化到 app_config 表 today_skip_count（{date,count} JSON），跨天自动归零。
	 *  与 break_skip_count（单次休息防误触、进休息清零、不持久化）严格区分。
	 *  AlertingView 据此 + skip_count_reminder 阈值决定是否显示「今日多次跳过休息」警示横幅。
	 */
	todaySkipCount: number,
	/**
	 *  已完成的工作-休息轮数。长休息判定输入：
	 *  `completed_cycles > 0 && completed_cycles % interval == 0`；
	 *  仅正常完成 on_break_done 才递增，跳过休息不计入。
	 */
	completedCycles: number,
	/**  当前 Paused 的触发来源（manual / quiet / dnd）。仅 phase == Paused 时有意义。 */
	pauseSource: PauseSource,
	/**
	 *  Breaking 阶段是否因检测到鼠标活动而软暂停（不切 phase，仅冻结倒计时）。
	 *  前端 BreakingView 据此显隐「检测到操作，倒计时已暂停」横幅。
	 */
	breakPaused: boolean,
	/**
	 *  本次 phase 切换是否由时段暂停结束自动恢复触发（quiet / dnd pause → 自动 start_work 新一轮）。
	 *  仅 phase-changed 事件中 Paused→Working 时有意义：panel.rs 据此决定收起而非显示工作窗口。
	 *  timer-tick / get_timer_state 恒为 false。
	 */
	autoResumed: boolean,
};

/**
 *  Y/N 布尔约定的 SSOT。
 * 
 *  serde rename 决定 DB 存储格式（"Y"/"N"）+ 前端 bindings.ts 字面量联合类型。
 *  前端 src/shared/appConfig.ts 的 YES_NO 运行时对象受此类型约束
 */
export type YesNo = "Y" | "N";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

